### ISSUE TITLE
Research back-end support on HostGator.com

### ISSUE THREAD

**Issue by boulderalf** [BeeSafeEarth/BeeSafeEarth#8]
Ideally we would have our front-end and back-end services on the same infrastructure.

Research what database and web service support is available on https://www.hostgator.com/

https://www.hostgator.com/dedicated

**Comment by boulderalf** [comment]
@ZebGirouard 

I do not know our projected front-end, back-end, database, and bandwidth usage, so it is difficult to compare the costs of HostGator and Amazon Web Services (AWS).  

I do know that AWS provides a free tier for the first year of a new account.  If we are going to go global with BeeSafeEarth, then it would probably be helpful to have a global [Content Delivery Network (CDN)](https://aws.amazon.com/cloudfront/) that makes the side responsive all around the earth.  My vote is to use AWS for all our web infrastructure.

We could do a phased transition where we keep the BeeSafeEarth.org on HostGator for the time being.  We could put the pledge form and database and web services on AWS and just `<iframe/>` the pledge form into HostGator-hosted pledge page.

What do you think?

cc @kristinreynolds @DaveLaskarzewski @Beesafedavid @autumnmartin

**Comment by Beesafedavid** [comment]
This seems logical to me.
bee safe david

> On Apr 28, 2016, at 8:40 AM, Alfred Sawatzky notifications@github.com wrote:
> 
> @ZebGirouard https://github.com/ZebGirouard
> I do not know our projected front-end, back-end, database, and bandwidth usage, so it is difficult to compare the costs of HostGator and Amazon Web Services (AWS).
> 
> I do know that AWS provides a free tier for the first year of a new account. If we are going to go global with BeeSafeEarth, then it would probably be helpful to have a global Content Delivery Network (CDN) https://aws.amazon.com/cloudfront/ that makes the side responsive all around the earth. My vote is to use AWS for all our web infrastructure.
> 
> We could do a phased transition where we keep the BeeSafeEarth.org on HostGator for the time being. We could put the pledge form and database and web services on AWS and just <iframe/> the pledge form into HostGator-hosted pledge page.
> 
> What do you think?
> 
> cc @kristinreynolds https://github.com/kristinreynolds @DaveLaskarzewski https://github.com/DaveLaskarzewski @Beesafedavid https://github.com/Beesafedavid @autumnmartin https://github.com/autumnmartin
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub https://github.com/BeeSafeEarth/BeeSafeEarth/issues/8#issuecomment-215447798

=== David Wheeler, Kansuke II ===
Musician (Shakuhachi) + Musicologist
3660 Buckeye Ct., Boulder, CO 80304 USA
shakudavid@gmail.com  
Cell: 720-545-5595
www.kansuke2.com http://www.kansuke2.com/

**Comment by ZebGirouard** [comment]
@boulderalf , I just set up a new AWS account with the following email:

tgirouar@alumni.cmu.edu

Apologies for the esoteric email address, but I've already used up the free tier on my two actual emails, and that one forwards to my personal gmail.  I can give you (and any future developers) the password over our next Google Hangout.

I have a slight preference to set us up with Ubuntu on EC2, with a NodeJS backend and a SQL DB of some sort.  I've never used Amazon RDS, but I'll try to lean on that as heavily as possible for the DB.  It's okay that Alfred is probably the only one who knows what all that means, please let me know if you have other preferences or suggestions.  

@Beesafedavid , @kristinreynolds , @DaveLaskarzewski , can we set up a quick call for the end of the week to go over current status of AWS and Hostgator?  I feel like we're drifting apart, and want to make sure we're on the same page.

**Comment by DaveLaskarzewski** [comment]
Hi Zeb, everyone. 

David is in Portugal but I can hop on a call on either Thursday or Friday this week. 

Dave

**Comment by Beesafedavid** [comment]
Hi All,
@Zeb, Thanks for checking in. I agree a sync up between front-end/back-end
is in order.
By early June, we plan/hope to have a functioning front-end, with lots of
info about what we do, materials for people to use, a pledge page, etc.
If mapping and storing pledges digitally can happen by then, great, if not,
we'll incorporate those and related features later, as they develop.
We don't want to wait any longer on a website because we are going to be
getting lots of publicity in June (eTown broadcast, etc.).
Re a hangout, I can do Thursday noonish or later, or Friday AM, I think.
I'll be traveling by car Thursday, so I can't promise. Also, Kristin is
away at a workshop now and won't be free until Thursday aft., and she is
doing a BSE presentation in Fort Collins Thu night.
So Friday might be better.
Zeb, can you make a call and send invites?
Waiting to hear back from Kristin may make it difficult to schedule. I'm
sure she'll join if she can, as she is interested in moving forward with a
website so we can beta test, etc.
See you all soon!
Cheers,
bsd

# 

David Wheeler, Kansuke II
Musician (Shakuhachi) + Musicologist
3660 Buckeye Ct., Boulder, CO 80304 USA
shakudavid@gmail.com
Cell: 720-545-5595
kansuke2.com

**Comment by ghost** [comment]
Hey everyone!

I probably won't be able to do a call this week, as I'm doing prep for some
pretty huge actions taking place this Thursday and Saturday (check out
co.breakfree2016.org if you wanna protest some fracking!). I walked Dave
through the website at our meeting a few days ago so he can answer some
front-end questions.

I'll try to hop on the call if I'm able.

Thanks,
Kristin

On Tuesday, May 10, 2016, Beesafedavid notifications@github.com wrote:

> Hi All,
> @Zeb, Thanks for checking in. I agree a sync up between front-end/back-end
> is in order.
> By early June, we plan/hope to have a functioning front-end, with lots of
> info about what we do, materials for people to use, a pledge page, etc.
> If mapping and storing pledges digitally can happen by then, great, if not,
> we'll incorporate those and related features later, as they develop.
> We don't want to wait any longer on a website because we are going to be
> getting lots of publicity in June (eTown broadcast, etc.).
> Re a hangout, I can do Thursday noonish or later, or Friday AM, I think.
> I'll be traveling by car Thursday, so I can't promise. Also, Kristin is
> away at a workshop now and won't be free until Thursday aft., and she is
> doing a BSE presentation in Fort Collins Thu night.
> So Friday might be better.
> Zeb, can you make a call and send invites?
> Waiting to hear back from Kristin may make it difficult to schedule. I'm
> sure she'll join if she can, as she is interested in moving forward with a
> website so we can beta test, etc.
> See you all soon!
> Cheers,
> bsd
> 
> # 
> 
> David Wheeler, Kansuke II
> Musician (Shakuhachi) + Musicologist
> 3660 Buckeye Ct., Boulder, CO 80304 USA
> shakudavid@gmail.com
> <javascript:_e(%7B%7D,'cvml','shakudavid@gmail.com');>
> Cell: 720-545-5595
> kansuke2.com
> 
> On Tue, May 10, 2016 at 5:23 AM, Zeb Tim Girouard <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
> 
> > @boulderalf https://github.com/boulderalf , I just set up a new AWS
> > account with the following email:
> > 
> > tgirouar@alumni.cmu.edu
> > <javascript:_e(%7B%7D,'cvml','tgirouar@alumni.cmu.edu');>
> > 
> > Apologies for the esoteric email address, but I've already used up the
> > free tier on my two actual emails, and that one forwards to my personal
> > gmail. I can give you (and any future developers) the password over our
> > next Google Hangout.
> > 
> > I have a slight preference to set us up with Ubuntu on EC2, with a NodeJS
> > backend and a SQL DB of some sort. I've never used Amazon RDS, but I'll
> > try
> > to lean on that as heavily as possible for the DB. It's okay that Alfred
> > is
> > probably the only one who knows what all that means, please let me know
> > if
> > you have other preferences or suggestions.
> > 
> > @Beesafedavid https://github.com/Beesafedavid , @kristinreynolds
> > https://github.com/kristinreynolds , @DaveLaskarzewski
> > https://github.com/DaveLaskarzewski , can we set up a quick call for
> > the end of the week to go over current status of AWS and Hostgator? I
> > feel
> > like we're drifting apart, and want to make sure we're on the same page.
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/BeeSafeEarth/BeeSafeEarth/issues/8#issuecomment-218049702
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/BeeSafeEarth/BeeSafeEarth/issues/8#issuecomment-218135112

## 

Kristin Reynolds
Director of Communication & Development, Bee Safe Boulder
Cell: (336) 653-0421

**Comment by ZebGirouard** [comment]
Back-end update with Amazon AWS: I successfully executed an INSERT and SELECT from our new, free, EC2 (web server) instance to our new, free, RDS (Database) today.

Now the task for me is sending my test form pledge data to this AWS backend which then gets INSERTed into a Pledges table.

I should have that end-to-end figured out by end of the weekend.  Looking forward to the call tomorrow.

**Comment by DaveLaskarzewski** [comment]
Hi Zeb. You are a bearer of glad tidings. 

Please keep track of your in-kind hours applied to helping Bee Safe along with your day rate. When we apply for grants, volunteer hours give us insight into future budget requirements and operating expenses, helping to justify our asks from foundations. 

Thank you, again, for all of your wonderful help and I hope that you and your wife are enjoying Colorado.

Dave 

david laskarzewski
social impact storyteller/
content strategist
720.560.0825

linkedin.com/in/laskarzewski

davidlaskarzewski.com

**Comment by Beesafedavid** [comment]
I'm having connectivity issues. I'll try to catch up. Sorry to miss the hangout after all. 
bsd

iPhone 720-545-5595
Shakudavid@gmail.com

**Comment by boulderalf** [comment]
I am closing this issue.  @ZebGirouard and I have decided that the best technical path going forward is to use Amazon Web Services in the future.  For the short term, we can still use Host Gator.  Once we have a site up on AWS, we can do a switch over.
