### ISSUE TITLE
Clone existing BeeSafeEarth web site into AWS

### ISSUE THREAD

**Issue by boulderalf** [BeeSafeEarth/BeeSafeEarth#9]
For the time being, we need to leave the HostGator-hosted http://www.beesafeearth.org/ as the production version.

To build a new version with pledge form and cool map, it is essential that we make a clone of the content of http://www.beesafeearth.org/ on our AWS development environment.

Once we have the clone up and running, we can send you the URL so you can view progress over the next weeks.

@ZebGirouard will have low to zero availability in June, so this request needs to be fulfilled ASAP.

@DaveLaskarzewski can you do a full site dump of the current www.beesafeearth.org site and send it to @ZebGirouard?  Can you have it completed by Monday morning?

cc @kristinreynolds @Beesafedavid

**Comment by boulderalf** [comment]
@ZebGirouard in case we do not get a timely response from Dave for Kristin, I am using https://www.httrack.com to clone a copy of beesafeearth.org.  Ideally we would still have access to the real source pages, but a ripped copy might be enough of a workaround for the time being.  I will upload the ripped site once it is done.

**Comment by boulderalf** [comment]
@ZebGirouard I made a copy of the website and uploaded it to the shared Google Drive.

**Comment by DaveLaskarzewski** [comment]
Hey folks. 

Attached is a wireframe of the Bee Safe Earth HP (the initial visual is video). My goal is to simplify and consolidate the UX of the nav bar and include a "Donate" button; it's a starting point and open for discussion....
